name: Deploy
on:
  push:
    branches:
      - develop
env:
  CI: true
jobs:
  run:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Set Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Version
        run: |
          node --version
          npm --version
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
